version: '3.5'

services:
    mariadb:
        image: mariadb:focal
        restart: always
        volumes:
            - ./mariadb-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: replaceme
  
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8000:80
        environment:
            - PMA_HOST=mariadb
        depends_on:
            - mariadb

networks:
    default:
        name: nginx
              